### ISSUE TITLE
Major Issue with Server Selection

### ISSUE THREAD

**Issue by gjsmith66** [CenturyLinkCloud/clc-node-sdk#197]
serverService
        .find({
            id:'',
        dataCenter: [DataCenter.US_EAST_STERLING],
        powerStates: ['paused', 'stopped'],
    })

This will match EVERY server.  it does NOT match server with an id of ''

**Comment by jruckle** [comment]
@idrabenia can you review this item and comment?

**Comment by jruckle** [comment]
Closing per @push1st1k
