### ISSUE TITLE
Time issues between UTC and EST

### ISSUE THREAD

**Issue by gjsmith66** [CenturyLinkCloud/clc-node-sdk#198]
Real-time monitoring statistics filtered by dataCenter and grouped by servers:
    statisticsService.monitoringStats({
        dataCenter: DataCenter.US_EAST_STERLING,
        groupBy: Resource.Server,
        timeFilter: {
            start: moment().subtract(1, 'hours'),
            end: moment(),
            sampleInterval: '15:00',
            type: compute.MonitoringStatsType.REALTIME
        }
    });

When running this code on a machine in EST, the following error is returned.

{ message: 'Realtime data is only available for four hours. Both the \'start\' and \'end\' parameters must be within four hours of the current time.\r\nParameter name: start' }
Unhandled rejection Error: Cannot GET https://api.ctl.io/v2/groups//xxx/statistics?start=2016-05-26T10:09:31&sampleInterval=00:00:15:00&type=realtime&end=2016-05-26T10:29:31

It looks like you are sending the dates in an incorrect format?

**Comment by gjsmith66** [comment]
Setting process.env.TZ = 'GMT'  will force it to work, however not a great solution.  It looks like the sdk is validating on local time, and CL is validating on GMT.

I would also have expected that the result would have been utilization by server, but it groups by Group, not server.  So, who knows...

**Comment by push1st1k** [comment]
@gjsmith66 
New version of SDK was released. Please update it and check that all works as expected.
